# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'zsailer'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'science', folder: 'pages', file: 'science.html'}
- {name: 'software', folder: 'pages', file: 'software.html'}
- {name: 'jupyter', folder: 'pages', file: 'jupyter.html'}
- {name: 'about', folder: 'pages', file: 'about.html'}
- {name: 'contact', folder: 'pages', file: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link: 'https://twitter.com/zrsailer'}
- {icon: 'github', link: 'https://www.github.com/Zsailer'}
- {icon: 'instagram', link: 'https://instagram.com/zsailer'}
- {icon: 'envelope', link: 'mailto:zachsailer@gmail.com'}
- {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
